[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

build_flags =
    -D LV_CONF_SKIP

lib_deps =
    bodmer/TFT_eSPI@^2.5.31
    lvgl/lvgl@^8.3.9
    adafruit/Adafruit BMP085 Library@^1.2.2
    
