[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

; Library များကို အသေးစိတ်ရှာဖွေရန်
lib_ldf_mode = deep 

build_flags =
    -D LV_CONF_SKIP
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MISO=-1
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=-1
    -D TFT_DC=13
    -D TFT_RST=10
    -D TFT_BL=-1
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=27000000

lib_deps =
    SPI
    Wire
    bodmer/TFT_eSPI@^2.5.31
    lvgl/lvgl@^8.3.9
    adafruit/Adafruit BMP085 Library@^1.2.2
    
